enable: §bTubeNekoPlugin 插件正在加载...
disable: §bTubeNekoPlugin 插件正在关闭...
error:
  not_player: §4你不是玩家!

command:
  here:
    enable: true
    message: §6玩家 %_ 在 §b[%_, %_, %_] §a@ %_
    time: 10
  lucky:
    enable: true
    range: 100
    message: §a今日人品：%_
  cat:
    enable: true
    message: o(=•ェ•=)m 喵~
  compass:
    enable: true
    message: §6你家在 §b[%_, %_, %_] §a@ %_

feature:
  sod:
    enable: true
    time: 3
    message:
      death: §a你死了  在 §b[%_, %_, %_] §a@ %_
      respawn: §a你将在 %_ 秒后重生...
