modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/MrCraftTeamMC/TubeNekoPlugin/issues"
license = "GPLv3"

[[mods]]
modId = "tubenekoplugin"
version = "${version}"
displayName = "TubeNekoPlugin"
displayURL = "https://tcbuildmc.xyz"
authors = "TCBuildTeamMC"
credits = "Block_limr267, Mr_zmh5, SnowCuiteQwQ"
description = '''
A server-side Mod / Plugin provides some mess features for Minecraft Servers. Used by TubeCraft.
'''
logoFile = "icon.png"

[[dependencies.tubenekoplugin]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tubenekoplugin]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tubenekoplugin]]
modId = "architectury"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
