name: Build and Test

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      discussions: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup jdk 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: gradle/wrapper-validation-action@v2

      - name: Fix Gradle permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --stacktrace --no-daemon

      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Read Properties mod info
        id: prop_info
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: "release_version"

      - name: Upload Artifacts
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: TubeNekoPlugin-${{ env.SHORT_SHA }}
          path: |
            mod/fabric/build/libs/*.jar
            mod/forge/build/libs/*.jar
            mod/neoforge/build/libs/*.jar
            plugin/bukkit/build/libs/*.jar
            plugin/bungeecord/build/libs/*.jar
            plugin/sponge/build/libs/*.jar
            plugin/velocity/build/libs/*.jar
